name: Run Mypy Type Checker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Mypy
        run: |
          pip install --upgrade pip
          pip install mypy

      - name: Run Mypy
        run: mypy .
